### ISSUE TITLE
Two library dependency issues and their workarounds

### ISSUE THREAD

**Issue by bsh-ableton** [Acciaiodigitale/homebrew-mint-lang#1]
Thanks for making Mint available for Homebrew!

There were two additional steps I had to take after using the formula, which I wanted to share in case they're not specific to my development environment.

## bdw-gc

I got the error:

```
dyld: Library not loaded: /usr/local/opt/bdw-gc/lib/libgc.1.dylib
  Referenced from: /usr/local/bin/mint-lang
  Reason: image not found
```

This was resolved by `brew install bdw-gc`, as per the [manual installation instructions](https://www.mint-lang.com/install).

It looks like this is a transitive dependency from [Crystal's Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/001bdbe2404f853c39da5e9fb184131874ebf843/Formula/crystal.rb#L41) that wasn't satisfied for some reason.

## libevent

I got the error:

```
dyld: Library not loaded: /usr/local/opt/libevent/lib/libevent-2.1.6.dylib
  Referenced from: /usr/local/bin/mint-lang
  Reason: image not found
Abort trap: 6
```

This was resolved by changing the binary's dependency to the more recent version installed by Homebrew: 

```bash
install_name_tool -change  /usr/local/opt/libevent/lib/libevent-2.1.6.dylib /usr/local/opt/libevent/lib/libevent-2.1.7.dylib /usr/local/bin/mint-lang 
```

## my system

I'm running macOS 10.14.6 (18G95), with Homebrew 2.1.11.

Many thanks!

**Comment by Acciaiodigitale** [comment]
Hi!

Thanks for the workarounds!

I've tested on the same version of Homebrew (2.1.11) on macOS 10.14.6 (18G87).

In my case is possible to obtain the same with only:
```
sudo install_name_tool -change  /usr/local/opt/libevent/lib/libevent-2.1.6.dylib /usr/local/opt/libevent/lib/libevent-2.1.7.dylib /usr/local/bin/mint-lang
```

**Comment by Acciaiodigitale** [comment]
This w.e. I see how to have this dome within brew command automatically

**Comment by Acciaiodigitale** [comment]
I close this because of Mint new version 0.6.0
