### ISSUE TITLE
Mint 0.7.0

### ISSUE THREAD

**Issue by gdotdesign** [Acciaiodigitale/homebrew-mint-lang#3]
Hey, just let you know that I've just released 0.7.0, If you can direct me on how to update this I would be happy to create PRs for future releases :slightly_smiling_face:

**Comment by Acciaiodigitale** [comment]
Hi Gusztáv.

For new release I have to update the binary on tar.gz and update the
version and sha256 field on the ruby configuration file.

Normally I'll do this in two steps:

I update version and binary, and on error I copy the sha Homebrew give me
in place of the old one.

So the release is finally correctly update.

Max

PS I try to do this already this evening. If you can plan the next releases
on the weekends we can relase for homebrew at the same time.


Il lun 9 dic 2019, 09:34 Szikszai Gusztáv <notifications@github.com> ha
scritto:

**Comment by gdotdesign** [comment]
Thanks for the info, I'll try to do it next time :+1:
